name: Docker Image CI

on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Extract metadata
      run: echo "BRANCH=${GITHUB_REF##*/}" >> $GITHUB_ENV
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build Frontend
      uses: docker/build-push-action@v2
      with:
        push: true
        context: ./frontend
        tags: ghcr.io/solid-polls/solid/solid-frontend:${{ env.BRANCH }}
    - name: Build Backend
      uses: docker/build-push-action@v2
      with:
        push: true
        context: ./backend
        tags: ghcr.io/solid-polls/solid/solid-backend:${{ env.BRANCH }}
    - name: Deploy
      uses: appleboy/ssh-action@master
      #if: ${{ env.BRANCH == 'main' }}
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        script: /root/update.sh